### ISSUE TITLE
Extra spacing around links

### ISSUE THREAD

**Issue by fdsimms** [lilykriopelle/THMSite#1]
There are extra spaces around the links in the Donate and Contact sections.
![thr_thing](https://cloud.githubusercontent.com/assets/12575341/16179542/e994d782-3636-11e6-985f-2294cd88f5be.gif)
![thr_thing2](https://cloud.githubusercontent.com/assets/12575341/16179543/ead4cc74-3636-11e6-8575-d55964769322.gif)

**Comment by lilykriopelle** [comment]
@fdsimms you win this time.
